services:
  indices_prep:
    build:
      context: .
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-TRACE}
      R_CONFIG_ACTIVE: ${R_CONFIG_ACTIVE:-2023Q4}
      BENCHMARK_DATA_FILEPATH: ${BENCHMARK_DATA_FILEPATH:-./inputs}
    volumes:
      - type: bind
        source: ${PACTA_DATA_PATH}
        target: /pacta-data/${R_CONFIG_ACTIVE}
        read_only: true
      - type: bind
        source: ${INDICES_PREPARATION_OUTPUTS_PATH:-./outputs}
        # target must be kept in sync with config.yml
        target: /mnt/outputs
        read_only: false
