version: "3"
services:
  indices_prep:
    build:
      context: .
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - R_CONFIG_ACTIVE=${R_CONFIG_ACTIVE}
    volumes:
      - type: bind
        source: ${PACTA_DATA_PATH}
        target: /pacta-data/${R_CONFIG_ACTIVE}
      - type: bind
        source: ${INDICES_PREPARATION_OUTPUTS_PATH:-./outputs}
        # target must be kept in sync with config.yml
        target: /mnt/outputs
