---
name: Run scenario preparation

# This workflow is based on, but diverges from the example here:
# https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners

on:
  workflow_call:
    inputs:
      image-tag:
        description: Tag for docker image
        required: true
        type: string
      data-share-path:
        description: Path on Azure Files to pacta-data
        required: true
        type: string
      config_active:
        description: active config from config.yml
        required: true
        type: string
    outputs:
      timestamp-dir:
        description: "Timestamped directory of workflow outputs"
        value: ${{ jobs.prep.outputs.timestamp-dir }}

jobs:
  prep:
    name: Run workflow
    runs-on: ubuntu-latest
    timeout-minutes: 45
    # write to packages (ghcr.io)
    permissions:
      packages: read
      contents: read
      id-token: write
    outputs:
      timestamp-dir: ${{ steps.upload-results.outputs.timestamp-dir }}

    steps:

      - name: Checkout workflow.prepare.pacta.indices
        uses: actions/checkout@v4
        with:
          repository: RMI-PACTA/workflow.prepare.pacta.indices
          token: ${{ secrets.REPO_PAT }}

      # https://github.com/Azure/login?tab=readme-ov-file#login-with-openid-connect-oidc-recommended
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # https://github.com/marketplace/actions/azure-cli-action#workflow-to-execute-an-azure-cli-script-of-a-specific-cli-version
      - name: Download pacta-data
        uses: azure/CLI@v2
        env:
          data_share_path: ${{ inputs.data-share-path }}
          pacta_data_quarter: ${{ inputs.config_active }}
        with:
          # azcliversion: 2.30.0
          inlineScript: |
            pacta_data_afs_path="https://pactadatadev.file.core.windows.net/workflow-data-preparation-outputs/$data_share_path/*"
            az storage copy \
              --source "$pacta_data_afs_path" \
              --destination "pacta-data/$pacta_data_quarter" \
              --recursive \
              --exclude-pattern "*.sqlite"

      - name: Prepare .env file
        env:
          pacta_data_quarter: ${{ inputs.config_active }}
        run: |
          echo "PACTA_DATA_PATH=./pacta-data/$pacta_data_quarter" > .env
          echo "INDICES_PREPARATION_OUTPUTS_PATH=./outputs" >> .env
          echo "R_CONFIG_ACTIVE=$pacta_data_quarter" >> .env
          echo "LOG_LEVEL=DEBUG" >> .env
          mkdir "outputs"
          cat .env

      - name: run container
        env:
          base_tag: ${{ inputs.image-tag }}
        run: |
          base_tag=$(echo "$base_tag" | tr -d '[:space:]')
          docker-compose build --build-arg="BASE_TAG=$base_tag" -t pacta-index-prep:$base_tag .

      - name: run container
        run: |
          docker-compose up

      # https://github.com/Azure/login?tab=readme-ov-file#login-with-openid-connect-oidc-recommended
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # https://github.com/marketplace/actions/azure-cli-action#workflow-to-execute-an-azure-cli-script-of-a-specific-cli-version
      - name: Upload Results
        id: upload-results
        uses: azure/CLI@v2
        with:
          # azcliversion: 2.30.0
          inlineScript: |
            outputs_dir="outputs"
            timestamp_dir="$(ls $outputs_dir)"
            echo "timestamp-dir=$timestamp_dir"
            echo "timestamp-dir=$timestamp_dir" >> "$GITHUB_OUTPUT"
            workflow_index_outputs_afs_path="https://pactadatadev.file.core.windows.net/workflow-prepare-pacta-indices-outputs"
            az storage copy \
              --source $outputs_dir/* \
              --destination "$workflow_index_outputs_afs_path" \
              --recursive
