---
name: Run Index preparation

# This workflow is based on, but diverges from the example here:
# https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners

on:
  workflow_call:
    inputs:
      image-tag:
        description: Tag for docker image
        required: true
        type: string
      data-share-path:
        description: Path on Azure Files to pacta-data
        required: true
        type: string
      config_active:
        description: active config from config.yml
        required: true
        type: string
    outputs:
      timestamp-dir:
        description: "Timestamped directory of workflow outputs"
        value: ${{ jobs.prep.outputs.timestamp-dir }}

jobs:
  prep:
    name: Run Index Preparation
    runs-on: ubuntu-latest
    timeout-minutes: 45
    # write to packages (ghcr.io)
    permissions:
      packages: read
      contents: read
      id-token: write
    outputs:
      timestamp-dir: ${{ steps.upload-results.outputs.timestamp-dir }}

    steps:

      - name: Checkout workflow.prepare.pacta.indices
        uses: actions/checkout@v4
        with:
          repository: RMI-PACTA/workflow.prepare.pacta.indices
          token: ${{ secrets.REPO_PAT }}

      # https://github.com/Azure/login?tab=readme-ov-file#login-with-openid-connect-oidc-recommended
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # https://github.com/marketplace/actions/azure-cli-action#workflow-to-execute-an-azure-cli-script-of-a-specific-cli-version
      - name: Download pacta-data
        uses: azure/CLI@v2
        env:
          data_share_path: ${{ inputs.data-share-path }}
          pacta_data_quarter: ${{ inputs.config_active }}
        with:
          # azcliversion: 2.30.0
          inlineScript: |
            pacta_data_afs_path="https://pactadatadev.file.core.windows.net/workflow-data-preparation-outputs/$data_share_path/*"
            az storage copy \
              --source "$pacta_data_afs_path" \
              --destination "pacta-data/$pacta_data_quarter" \
              --recursive \
              --exclude-pattern "*.sqlite"
      - name: Download benchmark inputs
        uses: azure/CLI@v2
        with:
          # azcliversion: 2.30.0
          inlineScript: |
            benchmark_data_afs_path="https://pactadatadev.file.core.windows.net/workflow-benchmark-preparation-outputs/*"
            az storage copy \
              --source "$benchmark_data_afs_path" \
              --destination "inputs" \
              --recursive

      - name: Prepare .env file
        env:
          pacta_data_quarter: ${{ inputs.config_active }}
        run: |
          echo "PACTA_DATA_PATH=./pacta-data/$pacta_data_quarter" > .env
          echo "INDICES_PREPARATION_INPUTS_PATH=./inputs" >> .env
          echo "INDICES_PREPARATION_OUTPUTS_PATH=./outputs" >> .env
          echo "R_CONFIG_ACTIVE=$pacta_data_quarter" >> .env
          echo "LOG_LEVEL=DEBUG" >> .env
          mkdir "outputs"
          cat .env

      - name: pull Docker base image
        env:
          base_tag: ${{ inputs.image-tag }}
        run: |
          docker pull ghcr.io/rmi-pacta/workflow.transition.monitor:${base_tag}

      - name: Hash files
        id: hash-files
        env:
          base_tag: ${{ inputs.image-tag }}
          config_active: ${{ inputs.config_active }}
        run: |
          tmpfile=$(mktemp)
          docker run --rm ghcr.io/rmi-pacta/workflow.transition.monitor:${base_tag} find /usr/local/lib/R/ -type f -exec md5sum {} \; >> "$tmpfile"
          docker run --rm ghcr.io/rmi-pacta/workflow.transition.monitor:${base_tag} find /bound -type f -exec md5sum {} \; >> "$tmpfile"
          docker run --rm ghcr.io/rmi-pacta/workflow.transition.monitor:${base_tag} find /pacta-data -type f -exec md5sum {} \; >> "$tmpfile"
          md5sum .env >> $tmpfile
          find pacta-data/ -type f -exec md5sum {} \; >> "$tmpfile"
          find inputs/ -type f -exec md5sum {} \; >> "$tmpfile"
          md5sum DESCRIPTION >> "$tmpfile"
          md5sum config.yml >> "$tmpfile"
          md5sum main.R >> "$tmpfile"
          cat $tmpfile
          overall_md5=$(md5sum "$tmpfile" | awk '{ print $1 }')
          echo "overall-md5=$overall_md5"
          echo "overall-md5=$overall_md5" >> "$GITHUB_OUTPUT"
          echo "hashfile=$tmpfile" >> "$GITHUB_OUTPUT"

      - uses: actions/upload-artifact@v4
        with:
          path: ${{ steps.hash-files.outputs.hashfile }}
          if-no-files-found: error

      - name: Check if results exist
        id: check-exist
        uses: azure/CLI@v2
        env:
          overall_md5: ${{ steps.hash-files.outputs.overall-md5 }}
        with:
          # azcliversion: 2.30.0
          inlineScript: |
            files_exist=$(
              az storage directory exists \
                --name "$overall_md5" \
                --share-name "workflow-prepare-pacta-indices-outputs" \
                --account-name "pactadatadev" |
                jq -rc '.exists'
            )
            echo "files-exist=$files_exist"
            echo "files-exist=$files_exist" >> "$GITHUB_OUTPUT"

      - name: build image
        if: ${{ steps.check-exist.outputs.files-exist != 'true' }}
        env:
          base_tag: ${{ inputs.image-tag }}
        run: |
          base_tag=$(echo "$base_tag" | tr -d '[:space:]')
          docker-compose build --build-arg="BASE_TAG=$base_tag" -t pacta-index-prep:$base_tag .

      - name: run container
        if: ${{ steps.check-exist.outputs.files-exist != 'true' }}
        run: |
          docker-compose up

      # https://github.com/Azure/login?tab=readme-ov-file#login-with-openid-connect-oidc-recommended
      - name: Azure Login
        if: ${{ steps.check-exist.outputs.files-exist != 'true' }}
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # https://github.com/marketplace/actions/azure-cli-action#workflow-to-execute-an-azure-cli-script-of-a-specific-cli-version
      - name: Upload Results
        id: upload-results
        uses: azure/CLI@v2
        env:
          overall_md5: ${{ steps.hash-files.outputs.overall-md5 }}
        with:
          # azcliversion: 2.30.0
          inlineScript: |
            outputs_dir="outputs"
            timestamp_dir="$overall_md5/$(ls $outputs_dir)"
            echo "timestamp-dir=$timestamp_dir"
            echo "timestamp-dir=$timestamp_dir" >> "$GITHUB_OUTPUT"
            workflow_index_outputs_afs_path="https://pactadatadev.file.core.windows.net/workflow-prepare-pacta-indices-outputs"
            az storage copy \
              --source $outputs_dir/* \
              --destination "$workflow_index_outputs_afs_path" \
              --recursive
